### ISSUE TITLE
Tax ID numbers

### ISSUE THREAD

**Issue by blssd2011** [agrc/api.mapserv.utah.gov#55] opened 2017-06-22 19:35 UTC
The older system was so easy to use for us and very useful.  With the recent change I cannot find/figure out if we are still able to find property by tax ID numbers.  I can search the address and the map takes me to the desired location but am not able to find the TaxID.
Please help

**Comment by steveoh** [comment] 2017-06-22 19:57
What map are you talking about @blssd2011 and what recent changes? Please reply with a link. 

This api hasn't changed for a few years. I'm wondering if you are referencing a different resource.

We will get this sorted out once you clarify a few things. Thanks for reaching out.

**Comment by blssd2011** [comment] 2017-06-23 14:23
I guess after clicking on a few things it had led me to this website.  the following is the site that I have been on for years and they have changed recently and is more difficult; http://raster.utah.gov/  .

**Comment by steveoh** [comment] 2017-06-23 14:26
@stdavis will you move this conversation to the raster repo and address the concerns please.

**Comment by stdavis** [comment] 2017-06-23 16:06
Hey @blssd2011. Thanks for reaching out. http://raster.utah.gov hasn't had any major changes in several years and has never had info on tax ID numbers. 

Perhaps you are looking for this site: http://parcels.utah.gov/ ? You should be able to search by address and then click on the parcel to get the tax ID number. Let me know if that works for you.

**Comment by steveoh** [comment] 2017-06-28 21:18
I am going to close this since it is out of the scope of the api.mapserv.utah.gov project. Please open a new issue in the repository of the project you are having issues with. Hopefully scotts comments will help you find tax id numbers. Otherwise we are guessing at where the issue is.

**Closed by steveoh** 2017-06-28 21:18 UTC
